sudo: required

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

install:
  - sudo apt-get install -y python-logilab-common
  - pip install pytest pytest-cov
  - pip install codecov

script:
  - pytest --version
  - pytest --cov=./

after_success:
  - codecov