language: python

python:
  - "2.7"
  - "3.4"

install:
  - pip install -U setuptools
  - pip install pytest pytest-cov
  - pip install codecov
  - python setup.py install

script:
  - pytest

after_success:
  - codecov